### ISSUE TITLE
Samples don't play - OSError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by ViktorNova** [rhetr/surplus#2]
Hey! I just stumbled on your plug for Surplus over on a Fabla thread. Cool stuff, however I'm having issues getting it to work. I get this console error every time I try and play a sample:

````                                 
QCoreApplication::postEvent: Unexpected null receiver          
QCoreApplication::postEvent: Unexpected null receiver          
QCoreApplication::postEvent: Unexpected null receiver          
Traceback (most recent call last):                             
  File "surplus", line 180, in mouseReleaseEvent               
    self.scene().changeDir(self.text)                          
  File "surplus", line 272, in changeDir                       
    self.drawContents()                                        
  File "surplus", line 296, in drawContents                    
    self.items[1].setSelected(True)                            
  File "surplus", line 134, in setSelected                     
    self.playSample()                                          
  File "surplus", line 126, in playSample                      
    self.playing = play(self.text)                             
  File "surplus", line 40, in play                             
    preexec_fn=os.setsid)                                      
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                              
    errread, errwrite)                                         
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child                                                       
    raise child_exception                                      
OSError: [Errno 2] No such file or directory                   
20686                                                          
finished making wave 
````
I ran it with python 2, as python 3 threw an error right away

**Comment by rhetr** [comment]
do you have sox installed? right now surplus relies on the 'play' command which is part of sox.

**Comment by ViktorNova** [comment]
Ah, that was it. Thanks! 
(sox isn't in listed as a dependency right now)
